ignore-paths:
    - doc
    - examples
    - test
    - utils

test-warnings: false

pylint:
    max-line-length: 120
    disable:
      - missing-docstring

pyflakes:
  run: false

pep8:
  run: false

mccabe:
  run: false

